env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-unused-vars:
    - error
    - vars: all
      args: all
      argsIgnorePattern: '^_'
      ignoreRestSiblings: false
  # ref: https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  # for Three.js
  react/no-unknown-property: off
settings:
  react:
    version: detect
